on:
    push:
      branches:
        - main
      tags-ignore:
        - '*'
  name: test
  jobs:
    test:
      runs-on: ubuntu-latest
      steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: build
        run: make get build